### ISSUE TITLE
chrome更新后无法使用，商店上无法打开解决方法

### ISSUE THREAD

**Issue by nakiyami** [ayamomiji/bookmark-tree#2]

**Comment by nakiyami** [comment]
修改manifest.json

{
  "manifest_version": 2,
  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",
  //add above
  "name": "__MSG_BookmarkTree__",
  "default_locale": "en",
  "version": "0.6.5",
  "description": "__MSG_Description__",
  "icons": {
    "128": "icon.png"
  },
  "browser_action": {
    "default_icon": "icon.png",
    "default_title": "__MSG_BookmarkTree__",
    "default_popup": "browser_action.html"          /*"popup": "browser_action.html"*/
  },
  "content_scripts": [
    {
      "matches": [ "http://*/*" ],
      "js": [ "content.js" ]
    }
  ],
  //"background_page": "background_page.html",
  "background":
	{
		
		"page": "background_page.html"
		
	},
  "options_page": "options_page.html",
  "permissions": [
    "http://*/*",
    "chrome://favicon/",
    "bookmarks",
    "tabs"
  ]
}

**Comment by nakiyami** [comment]
如果作者看到的话，希望能提交到商店吧。用你这书签很多年了，很好用~找了下替代品都不大满意。

**Comment by nakiyami** [comment]
不太会用github抱歉。。。
刚提交了manifest.json的修改到code。
自己用的下载下来compile后，扩展程序开发者模式加载文件夹应该就能用了。

**Comment by ayamomiji** [comment]
我發佈了重製的新版本:
https://chrome.google.com/webstore/detail/ayayas-bookmark-tree/dneehabidhbfdiohdhbhjbbljobchgab
